# XOR
XOR refrences the exclusive OR function found in digital logic

In [1]:
import torch 
import torch.nn as nn 
import torch.nn.functional as F 
import torch.optim as optim 

In [2]:
X = torch.Tensor([ [0, 0], [0, 1], [1, 0], [1, 1] ]) 
Y = torch.Tensor([ [0], [1], [1], [0] ]) 

print(X) 
print(Y)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0.],
        [1.],
        [1.],
        [0.]])


In [3]:
class XOR(nn.Module): 
    def __init__(self): 
        super(XOR, self).__init__() 
        self.lin1 = nn.Linear(2, 3, True) 
        self.lin2 = nn.Linear(3, 1, True) 
        
    def forward(self, x): 
        x = self.lin1(x) 
        x = F.relu(x) 
        x = self.lin2(x) 
        return x

In [4]:
model = XOR()

In [5]:
loss_func = nn.MSELoss() 
optimizer = optim.SGD(model.parameters(), lr=0.01,momentum=0.35)

In [6]:
epochs = 1000 
for idx in range(epochs): 
    for x,y in zip(X,Y): 
        optimizer.zero_grad()      # Zero the gradient buffers 
        y_hat = model(x)           # Make predictions 
        loss = loss_func(y_hat, y) # Compute the loss 
        loss.backward()            # Compute the gradients 
        optimizer.step()           # Does the update

In [7]:
model(X).relu()

tensor([[1.3411e-06],
        [1.0000e+00],
        [1.0000e+00],
        [9.8348e-07]], grad_fn=<ReluBackward0>)